added moonlight Palette
Schrodinger-Hat/ImageGoNord pull request #113
Opened 2022-08-28 18:10 UTC by Abod1960

# Pull Request

## Description

https://github.com/Schrodinger-Hat/ImageGoNord/labels/new-palette

@moonlight-theme is a dark color theme inspired by the camping vibe 🏕
and what I did is basically adding it to the palettes, I tested this locally*...

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

### Moonlight

![moonlight](https://user-images.githubusercontent.com/79435005/187086176-3b583f74-bf25-46f4-9219-e85c3b43714a.png)

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* IGN Version:

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2022-08-31 11:05 UTC, Wabri requested changes
Could you please rename the files without spaces?

Night sky.txt => NightSky.txt
White moon.txt => WhiteMoon.txt

Btw awesome palette 🚀

2022-08-31 11:16 UTC, Abod1960 commented
> Could you please rename the files without spaces?
> 
> Night sky.txt => NightSky.txt White moon.txt => WhiteMoon.txt
> 
> Btw awesome palette 🚀

done 💠

2022-09-05 09:29 UTC, Wabri requested changes
I add a suggestion for flair id of reddit 😁

2022-09-05 09:29 UTC, Wabri commented on reddit-posts-automation/auto-publish-multipalette.py
> +  'MOONLIGHT': {'id': '', 'hex_colors': ["#c0cedd", "#99a0a8", "#c6c3c0", "#191f28", "#1f2730", "#374656", "#ecbd7c", "#c69f68", "#93764d", "#c68768", "#c66868", "#c66890", "#6880c6","#68aec6","#9fc7
```suggestion
  'MOONLIGHT': {'id': '9bbf781a-2cfb-11ed-a549-1ac2767c974c', 'hex_colors': ["#c0cedd", "#99a0a8", "#c6c3c0", "#191f28", "#1f2730", "#374656", "#ecbd7c", "#c69f68", "#93764d", "#c68768", "#c66868", "#c66890", "#6880c6","#68aec6","#9fc76d"]},
```

2022-09-05 16:00 UTC, Wabri approved these changes

2022-09-05 16:00 UTC, merged