feat(palette): add Everforest palette to ImageGoWild
Schrodinger-Hat/ImageGoNord pull request #160
Opened 2024-05-20 19:17 UTC by JonathanBytes

# Pull Request

## Description

Add the Everforest colorscheme (the dark medium variant) based on this [Everforest Repo](https://github.com/sainnhe/everforest)

Fixes the web part of this issue #131 (**CLI remaining**)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings

2024-05-20 19:22 UTC, TheJoin95 approved these changes

2024-05-22 09:10 UTC, Wabri requested changes
Could you please change the image with something non development related? We should consider changing all of them into something more generic!

2024-05-22 22:40 UTC, JonathanBytes commented
Of course, I used that image trying to follow the other palettes. But I love the Idea, would be clearer.

2024-05-23 06:52 UTC, Wabri approved these changes
![image](https://github.com/Schrodinger-Hat/ImageGoNord/assets/12409541/cadba1ee-0cb1-43c3-83dd-d652ccf9bf7a)

Awesome, GG!

2024-05-23 06:53 UTC, merged