Feat(ai): first implementation of the PaletteNet algorithm managed from image-go-nord package
Schrodinger-Hat/ImageGoNord pull request #162
Opened 2024-05-23 21:37 UTC by TheJoin95

# Pull Request

Closes #157 

## Description

This is the first implementation of the AI model PaletteNet available from the image-go-nord package.
It's accepting a palette of 6 colors and it's then converting it using the model made in pytorch.

A second phase would convert the pytorch model into javascript model in order to be executed on the client side.
It will be discovered in a different issue.

Documentation will be updated in a follow-up ticket.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] tested locally

It needs to be tested on prod, as we need to update and get the code on our VPS.

**Test Configuration**:
* Firmware version: any
* Hardware: any
* Toolchain: Python, Vue
* IGN Version: 1.1.0

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2024-05-23 21:39 UTC, TheJoin95 commented
This pr has done a long journey but I'm happy to make it online

2024-05-27 15:20 UTC, Wabri requested changes
Little changes and I'm in your hands for the css staff. Huge work!

2024-05-27 15:28 UTC, TheJoin95 commented on src/ign-api/conversion.py
> +  if (request.form.get('is_ai') != None):
Totally and I agree with you

2024-05-27 15:44 UTC, TheJoin95 commented on src/ign-api/conversion.py
> +    job = q.enqueue(f=convert_image, ttl=900, failure_ttl=900, job_timeout='180s', args=(go_nord, image, output_path, request.form.get('b64_output'), response, use_model))
Let's keep it as they are, we might need to do some changes in the near future to this queue logic

2024-05-27 15:46 UTC, TheJoin95 commented on src/ign-frontend/src/components/Demo.vue
> +      this.selectedColor = p?.colors;
Old code from a WIP commit: there will be always a `colors` key in the palette object.
Thanks for the catch

2024-05-27 16:04 UTC, Wabri approved these changes

2024-05-27 16:04 UTC, merged